apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: taskboard-api
    newName: ghcr.io/your-github-user/taskboard-api
    newTag: v1.0.0
  - name: taskboard-frontend
    newName: ghcr.io/your-github-user/taskboard-frontend
    newTag: v1.0.0
patches:
  - target:
      kind: Deployment
      name: taskboard-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: StatefulSet
      name: taskboard-postgres
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 5Gi
